language: node_js
node_js:
  - "node"
  - "6.0"
sudo: false
before_install:
  - "npm install react@15 react-dom@15"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/eacdc382fb52d269de7c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
script:
  - npm test && npm run codecov
